Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,38 +1,28 @@
-name: Deploy
+#!/usr/bin/env sh
 
-on:
-  push:
-    branches:
-      - main
+# abort on errors
+set -e
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+# build
+npm run build
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '14'
+# navigate into the build output directory
+cd dist
 
-      - name: Install dependencies
-        run: npm install
+# если вы деплоите на кастомный домен
+# echo 'www.example.com' > CNAME
 
-      - name: Build
-        run: npm run build
+git init
+git add -A
+git commit -m 'deploy'
 
-      - name: Deploy to gh-pages
-        run: |
-          git config --global user.email "your email"
-          git config --global user.name "your github username"
+# если вы деплоите на https://<USERNAME>.github.io
+# git push -f git@github.com:Clarus2137/Clarus2137.github.io.git master
 
-          git checkout --orphan gh-pages
-          git rm -rf .
-          git add -f dist
-          git commit -m "Deploy to gh-pages"
+# если вы деплоите на https://Clarus2137.github.io/<REPO>
+git push -f git@github.com:dream-agency/Clarus2137.git master:gh-pages
 
+cd -
           # Используйте токен для аутентификации в URL-адресе репозитория
           git push -f https://$GH_TOKEN@github.com/Clarus2137/dream-agency.git gh-pages
         env:
